apiVersion: v1
kind: Service
metadata:
  name: aqua-events
  labels:
    app: aqua-events
spec:
  ports:
    - name: web
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: aqua-events
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-events
  template:
    metadata:
      labels:
        app: aqua-events
    spec:
      containers:
        - name: aqua-events
          image: bkmorrow/aqua-events-go:latest
          imagePullPolicy: Always
          env:
            - name: SLACK_WEBHOOK
              value: "<SLACK WEHBOOK GOES HERE>"
            - name: IGNORE_LIST
              # alert,success,detect,block
              value: "<CSV list of ignored events>"
